services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    init: true
    volumes:
      - ..:/workspaces/metactl:cached
    working_dir: /workspaces/metactl
