use super::*;

pub(super) fn cmd_hook(cli: &Cli, args: &HookArgs) -> std::result::Result<CommandOutput, CliError> {
    match &args.command {
        HookCommand::Install(install_args) => cmd_hook_install(cli, install_args),
        HookCommand::Status => cmd_hook_status(cli),
    }
}

fn cmd_hook_install(
    cli: &Cli,
    args: &HookInstallArgs,
) -> std::result::Result<CommandOutput, CliError> {
    let project_root = project_root(cli).map_err(internal_error)?;
    let git_hooks_dir = project_root.join(".git").join("hooks");
    if !git_hooks_dir.parent().map(|p| p.exists()).unwrap_or(false) {
        return Err(CliError::new(
            EXIT_STATE,
            "No .git directory found. This command requires a git repository.",
        ));
    }
    fs::create_dir_all(&git_hooks_dir)
        .map_err(|e| internal_error(anyhow::anyhow!("create .git/hooks: {}", e)))?;

    let hook_names: Vec<String> = if args.hooks.is_empty() {
        vec!["post-checkout".to_string(), "post-merge".to_string()]
    } else {
        args.hooks.clone()
    };

    let hook_script = r#"#!/bin/sh
# metactl sync hook — auto-generated by `metactl hook install`
# Runs metactl sync when config files change in a checkout or merge.

# Skip in detached HEAD state (e.g. CI, rebase)
if ! git symbolic-ref -q HEAD >/dev/null 2>&1; then
    exit 0
fi

# Check if metactl is available
if ! command -v metactl >/dev/null 2>&1; then
    echo "[metactl] metactl not found on PATH, skipping sync"
    exit 0
fi

METACTL_FILES="metactl.yaml metactl.local.yaml metactl.lock.json"
CHANGED=0
# HEAD@{1} may not exist on first checkout or shallow clone — skip gracefully
if git rev-parse --verify HEAD@{1} >/dev/null 2>&1; then
    for f in $METACTL_FILES; do
        if git diff HEAD@{1} --name-only 2>/dev/null | grep -q "^${f}$"; then
            CHANGED=1
            break
        fi
    done
fi

if [ "$CHANGED" = "1" ]; then
    echo "[metactl] Config changed, running sync..."
    metactl sync --yes --quiet || true
fi
"#;

    let mut installed = Vec::new();
    let mut skipped = Vec::new();
    for hook_name in &hook_names {
        let hook_path = git_hooks_dir.join(hook_name);
        if hook_path.exists() {
            let existing = fs::read_to_string(&hook_path).unwrap_or_default();
            if existing.contains("metactl") {
                skipped.push(format!("{} (already contains metactl hook)", hook_name));
                continue;
            }
            // Append to existing hook
            let mut combined = existing;
            if !combined.ends_with('\n') {
                combined.push('\n');
            }
            combined.push_str("\n# metactl sync hook — appended by `metactl hook install`\n");
            combined.push_str(&hook_script.lines().skip(1).collect::<Vec<_>>().join("\n"));
            combined.push('\n');
            atomic_write(&hook_path, combined.as_bytes()).map_err(|e| {
                internal_error(anyhow::anyhow!("write {}: {}", hook_path.display(), e))
            })?;
        } else {
            atomic_write(&hook_path, hook_script.as_bytes()).map_err(|e| {
                internal_error(anyhow::anyhow!("write {}: {}", hook_path.display(), e))
            })?;
        }
        // Make executable on unix
        #[cfg(unix)]
        {
            let metadata = fs::metadata(&hook_path).map_err(|e| {
                internal_error(anyhow::anyhow!(
                    "read metadata {}: {}",
                    hook_path.display(),
                    e
                ))
            })?;
            let mut perms = metadata.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&hook_path, perms).map_err(|e| {
                internal_error(anyhow::anyhow!("chmod {}: {}", hook_path.display(), e))
            })?;
        }
        installed.push(hook_name.clone());
    }

    let mut lines = Vec::new();
    if !installed.is_empty() {
        lines.push(format!("Installed hook(s): {}", installed.join(", ")));
    }
    if !skipped.is_empty() {
        lines.push(format!("Skipped: {}", skipped.join(", ")));
    }
    if installed.is_empty() && skipped.is_empty() {
        lines.push("No hooks to install.".to_string());
    }

    Ok(CommandOutput {
        human: project_human_output(&project_root, lines.join("\n")),
        json: success_json(
            "hook",
            Some(&project_root),
            json!({
                "action": "install",
                "installed": installed,
                "skipped": skipped,
            }),
        ),
    })
}

fn cmd_hook_status(cli: &Cli) -> std::result::Result<CommandOutput, CliError> {
    let project_root = project_root(cli).map_err(internal_error)?;
    let git_hooks_dir = project_root.join(".git").join("hooks");

    let hook_names = ["post-checkout", "post-merge", "pre-commit", "pre-push"];
    let mut hooks = Vec::new();

    for hook_name in &hook_names {
        let hook_path = git_hooks_dir.join(hook_name);
        let exists = hook_path.exists();
        let has_metactl = if exists {
            fs::read_to_string(&hook_path)
                .map(|content| content.contains("metactl"))
                .unwrap_or(false)
        } else {
            false
        };
        hooks.push(json!({
            "hook": hook_name,
            "exists": exists,
            "has_metactl": has_metactl,
        }));
    }

    let mut lines = vec!["Hook status:".to_string()];
    for hook in &hooks {
        let name = hook["hook"].as_str().unwrap_or("?");
        let exists = hook["exists"].as_bool().unwrap_or(false);
        let has_metactl = hook["has_metactl"].as_bool().unwrap_or(false);
        let status = if has_metactl {
            "metactl"
        } else if exists {
            "exists (no metactl)"
        } else {
            "not installed"
        };
        lines.push(format!("  {:<16} {}", name, status));
    }

    Ok(CommandOutput {
        human: project_human_output(&project_root, lines.join("\n")),
        json: success_json(
            "hook",
            Some(&project_root),
            json!({
                "action": "status",
                "hooks": hooks,
            }),
        ),
    })
}
