//! Fleet planning stages generated bytes outside every participating project.
//! It uses the real context for source/profile resolution and real destinations
//! for adoption decisions; ordinary `sync --preview` has different write behavior.
use super::*;

pub(super) fn preview_project(
    project_root: &Path,
    context: &metactl::project::ProjectContext,
    adopt: FleetSyncAdoptMode,
) -> Result<Value> {
    let audit = source_audit_findings(project_root).map_err(|err| anyhow!(err.message))?;
    if !audit.is_empty() {
        return Err(anyhow!(
            "source audit failed: {}",
            source_audit_detail_lines(&audit).join("; ")
        ));
    }
    // A preview never fetches into source caches. Remote freshness remains an
    // apply-time check; local pinned source state is still checked here.
    let source_state = private_source_readiness(project_root, &context.config_file, false)
        .map_err(|err| anyhow!(err.message))?;
    if source_state["state"] == "private_source_stale" {
        return Err(anyhow!("private source is stale: {source_state}"));
    }
    let targets = context
        .config_file
        .targets
        .iter()
        .map(|target| resolve_target_alias(target, context.registry.as_ref()).0)
        .collect::<Vec<_>>();
    let overrides = ConfigOverrides {
        role: None,
        policy: None,
        targets: targets.clone(),
    };
    let discoverability = discoverability_report(context, &overrides);
    if discoverability.is_blocked() {
        return Err(anyhow!(discoverability_error(&discoverability).message));
    }
    let shared = shared_surface_rules(context.registry.as_ref(), &targets);
    let kernel = kernel_from_context(context)?;
    let staging = tempfile::tempdir().context("create fleet preview staging")?;
    let mut plans = Vec::new();
    for id in targets {
        let overrides = ConfigOverrides {
            role: None,
            policy: None,
            targets: vec![id],
        };
        let config = context.effective_config(&overrides)?;
        let surface_selection_mode = config
            .defaults
            .as_ref()
            .and_then(|defaults| defaults.surface_selection_mode.clone());
        let target = context
            .selected_targets(&overrides)?
            .into_iter()
            .next()
            .ok_or_else(|| anyhow!("target selection produced no target"))?;
        let preferred = preferred_apply_mode_for_target(&target, None);
        let graph = kernel.resolve(ResolveParams {
            config,
            overlay: context.overlay.clone(),
            available_targets: vec![target.clone()],
            provenance: None,
        })?;
        let mut compiled = kernel.compile(CompileParams {
            resolve_graph: graph,
            target_capability: target.clone(),
            apply_mode: preferred.clone(),
            surface_selection_mode,
            emit_policy_report: true,
            durable_staging: false,
            project_root: Some(staging.path().to_string_lossy().to_string()),
        })?;
        apply_shared_surface_rules_to_manifest(
            staging.path(),
            &target.target_id,
            &mut compiled.compile_manifest,
            &shared,
        )?;
        let requested_mode = (adopt == FleetSyncAdoptMode::Patch).then_some(ApplyMode::Patch);
        let (mode, _) = normalize_apply_mode(
            requested_mode,
            &preferred,
            &compiled.compile_manifest,
            Some(&target),
        )
        .map_err(|err| anyhow!(err.message))?;
        let (review, conflicts) = kernel.preview_compiled_outputs(
            project_root,
            staging.path(),
            &compiled.compile_manifest,
            &mode,
        )?;
        if !conflicts.is_empty() {
            return Err(anyhow!(
                "destination conflicts: {}",
                serde_json::to_string(&conflicts)?
            ));
        }
        let files = compiled
            .compile_manifest
            .generated_outputs
            .iter()
            .filter_map(|output| output.destination_path.clone())
            .collect::<Vec<_>>();
        let skill_count = files
            .iter()
            .filter(|path| path.ends_with("/SKILL.md"))
            .count();
        plans.push(json!({
            "target": target.target_id, "apply_mode": mode,
            "planned_output_files": files, "planned_skill_count": skill_count,
            "actions": review.actions,
        }));
    }
    Ok(json!({
        "status": "planned", "targets": plans, "remote_freshness_checked": false,
        "limitations": ["Preview is not an apply authorization; filesystem access and source freshness are checked again during apply."],
    }))
}
